services:
  app:
    build: .
    environment:
      HTTP_ADDR: ":8080"
      DB_DSN: "postgres://commerce:commerce@db:5432/commerce?sslmode=disable"
      SHUTDOWN_TIMEOUT_SECONDS: "10"

  dev-base:
    build:
      context: .
      target: dev
    working_dir: /workspace
    environment:
      HTTP_ADDR: ":8080"
      DB_DSN: "postgres://commerce:commerce@db:5432/commerce?sslmode=disable"
      SHUTDOWN_TIMEOUT_SECONDS: "10"
    volumes:
      - .:/workspace
