services:
  app-base:
    environment:
      HTTP_ADDR: ":8080"
      DB_DSN: "postgres://commerce:commerce@db:5432/commerce?sslmode=disable"
      SHUTDOWN_TIMEOUT_SECONDS: "10"
      MEDIA_ROOT: "/srv/media"
      MEDIA_BASE_URL: "media"
      FILE_URL_HOST: ${FILE_URL_HOST:-localhost:8080}

  app:
    extends:
      service: app-base
      target: prod
    build: .

  dev-base:
    build:
      context: .
      target: dev
    working_dir: /workspace
    environment:
      HTTP_ADDR: ":8080"
      DB_DSN: "postgres://commerce:commerce@db:5432/commerce?sslmode=disable"
      SHUTDOWN_TIMEOUT_SECONDS: "10"
      MEDIA_ROOT: "/workspace/media"
      MEDIA_BASE_URL: "media"
      FILE_URL_HOST: localhost:8080
    volumes:
      - .:/workspace
      - ./_gocache/mod:/go/pkg/mod
      - ./_gocache/build:/root/.cache/go-build

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: commerce
      POSTGRES_USER: commerce
      POSTGRES_PASSWORD: commerce
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U commerce -d commerce"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  db_data:
