services:
  db:
    extends:
      file: docker-compose.app.yml
      service: db

  migrate:
    extends:
      file: docker-compose.app.yml
      service: app-base
    image: ${API_IMAGE:-ghcr.io/andmedoctopus/commerce-tools-replica:latest}
    volumes:
      - ./media:/srv/media
      - ./imports:/srv/imports
    depends_on:
      db:
        condition: service_healthy
    entrypoint: ["/srv/migrate"]

  api:
    extends:
      file: docker-compose.app.yml
      service: app-base
    image: ${API_IMAGE:-ghcr.io/andmedoctopus/commerce-tools-replica:latest}
    volumes:
      - ./media:/srv/media
    depends_on:
      migrate:
        condition: service_completed_successfully
      db:
        condition: service_healthy

  nginx:
    image: nginx:1.27-alpine
    restart: unless-stopped
    depends_on:
      api:
        condition: service_started
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./media:/srv/media
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./nginx/sites-enabled:/etc/nginx/sites-enabled
      - ./nginx/sites-available:/etc/nginx/sites-available
      - ./certbot/www/:/var/www/certbot/
      - ./certbot/conf/:/etc/nginx/ssl/
      - /var/log/nginx:/var/log/nginx

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/
      - ./certbot/conf/:/etc/letsencrypt/
      - ./certbot/log:/var/log/letsencrypt

volumes:
  db_data:
