services:
  db:
    extends:
      file: docker-compose.app.yml
      service: db

  migrate:
    extends:
      file: docker-compose.app.yml
      service: app-base
    image: ${API_IMAGE:-ghcr.io/andmedoctopus/commerce-tools-replica:latest}
    volumes:
      - ./media:/srv/media
      - ./imports:/srv/imports
    depends_on:
      db:
        condition: service_healthy
    command: /srv/migrate

  api:
    extends:
      file: docker-compose.app.yml
      service: app-base
    image: ${API_IMAGE:-ghcr.io/andmedoctopus/commerce-tools-replica:latest}
    volumes:
      - ./media:/srv/media
    depends_on:
      migrate:
        condition: service_completed_successfully
      db:
        condition: service_healthy
    command: /srv/api
    healthcheck:
      test: curl -f localhost:8081/readyz
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

  ctr-nginx:
    image: nginx:1.27-alpine
    restart: unless-stopped
    depends_on:
      api:
        condition: service_healthy
    ports:
      - 9000:9000
    volumes:
      - ./media:/srv/media
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./nginx/sites-enabled:/etc/nginx/sites-enabled
      - ./nginx/sites-available:/etc/nginx/sites-available
      - /var/log/nginx:/var/log/nginx

volumes:
  db_data:
